<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda [
<!ELEMENT agenda (contacto*)>
<!ELEMENT contacto (nombre, telefonoFijo*, telefonoMovil+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT telefonoFijo (#PCDATA)>
<!ELEMENT telefonoMovil (#PCDATA)>
]>
<agenda>
<contacto>
<nombre>Ayuntamiento</nombre>
<telefonoFijo>010</telefonoFijo>
<telefonoMovil>123</telefonoMovil>
</contacto>
<contacto>
<nombre>Emergencias</nombre>
<telefonoFijo>112 (Unión Europea)</telefonoFijo>
<telefonoFijo>911 (Estados Unidos)</telefonoFijo>
<telefonoMovil>Desconocido</telefonoMovil>
</contacto>
</agenda>

<!--José Jiménez Romero-->

<!--He añadido la etiqueta telefonomovil en la primera etiqueta nombre ya que hemos declarado que tiene que ir dentro de nombre obligatoriamente-->